#ifndef CONFIG_H_
#define CONFIG_H_

#define EMULATOR_WINDOW_TITLE "Chip-8 Emulator"

#define DISPLAY_WIDTH 64
#define DISPLAY_HEIGHT 32
#define DISPLAY_SCALE 10

#define MEMORY_SIZE 4096
#define TOTAL_DATA_REGISTERS 16
#define TOTAL_STACK_DEPTH 16
#define TOTAL_KEYS 16
#define CHIP8_CHARACTER_SET_LOAD_ADDRESS 0x00
#define PROGRAM_LOAD_ADDRESS 0x200

#endif